### PR TITLE
Document building from source

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Well actually that does not work for me. I never touched maven and im not a java dude. Could you please provide detailed instructions on building. Because I always get manifest errors:

```
$ java -jar ./target/minecraft-world-downloader-1.0.jar -s localhost
no main manifest attribute, in ./target/minecraft-world-downloader-1.0.jar
```

**Comment by ChillerDragon** [comment]
Guess this should be a issue not a pullrequest. I also tried editing in the ``META-INF/MANIFEST.MF`` and added the missing ``Main-Class: Launcher`` but it still fails:

```
$ java -jar target/minecraft-world-downloader-1.0.jar                                                                                               
Error: Unable to initialize main class Launcher
Caused by: java.lang.NoClassDefFoundError: net/sourceforge/argparse4j/inf/ArgumentParserException
```

**Comment by mircokroon** [comment]
It's close, the last two lines should be replaced by:
```
mvn assembly:assembly
java -jar ./target/world-downloader.jar -s address.to.server.com
```

I believe `mvn install` is used to setup the dev environment while the `assembly` plugin is for building runnable jar files (as you'd want if you're not running it from an IDE).


I'd like to keep the basic install instructions central, though adding build instructions is definitely a good idea. If you want I could close this PR and add them to the bottom of the readme myself as well.

**Comment by mircokroon** [comment]
I added a little bit detail and changed wget link to always get the latest.

**Pull request merged**
