### PR TITLE
Improved version handling, added 1.16 support

### LINKED ISSUE #23: Minecraft 1.16 support
Unsurprinsingly, the latest release doesn't work with Minecraft 1.16 prerelease servers. Here is an error log.

```
Successfully authenticated user with Mojang session server.
User identity confirmed with Mojang.
Enabled encryption
Enabled compression
java.lang.ArrayIndexOutOfBoundsException: Index 28 out of bounds for length 28
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:94)
        at packets.builder.ClientBoundLoginPacketBuilder.lambda$new$2(ClientBoundLoginPacketBuilder.java:33)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:113)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:110)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.run(ProxyServer.java:68)
java.lang.ArrayIndexOutOfBoundsException: Index 52 out of bounds for length 52
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:94)
        at packets.builder.ClientBoundLoginPacketBuilder.lambda$new$2(ClientBoundLoginPacketBuilder.java:34)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:113)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:110)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.run(ProxyServer.java:68)
Login success: [redacted] logged in with uuid [redacted]
Using protocol of game version 1.15.0 (725)
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider$1.read(DataTypeProvider.java:166)
        at java.base/java.io.InputStream.read(Unknown Source)
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at se.llbit.nbt.StringTag.read(StringTag.java:46)
        at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
        at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:163)
        at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:39)
        at game.data.chunk.Chunk.parse(Chunk.java:257)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.Chunk.parse(Chunk.java:263)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider$1.read(DataTypeProvider.java:166)
        at java.base/java.io.InputStream.read(Unknown Source)
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at se.llbit.nbt.StringTag.read(StringTag.java:46)
        at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
        at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:163)
        at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:39)
        at game.data.chunk.Chunk.parse(Chunk.java:257)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.Chunk.parse(Chunk.java:263)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[2]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:79)
        at packets.DataTypeProvider.readDouble(DataTypeProvider.java:184)
        at packets.builder.ServerBoundGamePacketBuilder.lambda$new$0(ServerBoundGamePacketBuilder.java:13)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:93)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:90)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider$1.read(DataTypeProvider.java:166)
        at java.base/java.io.InputStream.read(Unknown Source)
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at se.llbit.nbt.StringTag.read(StringTag.java:46)
        at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
        at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:163)
        at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:39)
        at game.data.chunk.Chunk.parse(Chunk.java:257)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.Chunk.parse(Chunk.java:263)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider$1.read(DataTypeProvider.java:166)
        at java.base/java.io.InputStream.read(Unknown Source)
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at se.llbit.nbt.StringTag.read(StringTag.java:46)
        at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
        at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:163)
        at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:39)
        at game.data.chunk.Chunk.parse(Chunk.java:257)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.Chunk.parse(Chunk.java:263)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider$1.read(DataTypeProvider.java:166)
        at java.base/java.io.InputStream.read(Unknown Source)
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at se.llbit.nbt.StringTag.read(StringTag.java:46)
        at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
        at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:163)
        at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:39)
        at game.data.chunk.Chunk.parse(Chunk.java:257)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.Chunk.parse(Chunk.java:263)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at packets.DataTypeProvider$1.read(DataTypeProvider.java:166)
        at java.base/java.io.InputStream.read(Unknown Source)
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at se.llbit.nbt.StringTag.read(StringTag.java:46)
        at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
        at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:163)
        at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:39)
        at game.data.chunk.Chunk.parse(Chunk.java:257)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.Chunk.parse(Chunk.java:263)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:178)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:128)
Chunk could not be parsed!
```

### LINKED ISSUE #24: Default Gamerules to values that won't modify the world
I think it would be a good idea to let all gamerules of downloaded worlds default to values that minimize change of the world to preserve the state that the world was downloaded in.
This would include
- random tick speed 0
- domobspawning false
- daylightcycle false
- weathercycle false
- mobgriefing false

### PR DESCRIPTION
**Pull request by mircokroon**
- Added support for 1.16.0 and 1.16.1
- Any new versions will now download the corresponding server.jar and generate reports for entity and block IDs. This way they don't need to be included in the resources for this project and updating is a bit easier.
- Added default gamerules

Closes #23 
Closes #24

### CODE REVIEW

**Comment by mircokroon** [comment]
@ChillerDragon could you check if this works on Linux (on any version above 1.12.2)? I'm not sure how OS dependent the downloading/running processes/moving files code is so it'd be good to verify that it works well.

The first time you run it with a version it should say something in the console about downloading the server.jar, generating reports etc. Subsequent launches with the version shouldn't as it'll store the result.

**Comment by ChillerDragon** [comment]
Crash on connect. It claims not to find a file that should exist.

```
java -jar target/world-downloader.jar -s lgl.zillyhuhn.com
Starting proxy for lgl.zillyhuhn.com. Make sure to connect to localhost:25565 instead of the regular server address.
Performed handshake with lgl.zillyhuhn.com:25565, protocol version 578 :: next state: login
Login by: ChillerDragon
java.nio.file.NoSuchFileException: ~/.minecraft/launcher_profiles.json
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:374)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:425)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:159)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2915)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3393)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3433)
        at proxy.auth.ClientAuthenticator.getFile(ClientAuthenticator.java:47)
        at proxy.auth.ClientAuthenticator.<init>(ClientAuthenticator.java:28)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$7(EncryptionManager.java:250)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:93)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:250)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:238)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:80)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:227)
        at packets.builder.ServerBoundLoginPacketBuilder.lambda$new$1(ServerBoundLoginPacketBuilder.java:28)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:93)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:90)
        at java.base/java.lang.Thread.run(Thread.java:830)
Cannot read or find '~/.minecraft/launcher_profiles.json'!
Use launch option: "-m /path/to/.minecraft/" to indicate the location of your Minecraft installation.
```
```
chiller@debian:~/Desktop/git/minecraft-world-downloader$ ls ~/.minecraft/launcher_profiles.json
/home/chiller/.minecraft/launcher_profiles.json
```

**Comment by mircokroon** [comment]
That's weird, not actually related to anything that was changed I think.

Other than that it all works fine?

**Comment by ChillerDragon** [comment]
Tests went without crashes :tada: (I have a really slow connection so downloading the updates took some time haha)

tested on 1.15.2 and worked fine so far on the server
but 1.16.1 i also tried to load the world in single player and it threw a warning about the world being still in 1.16.0 and the new nether blocks I placed in the overworld were gone :/

I thought if you feel extra motivated you could maybe show something in the ui while the server is downloading so ui users know its doing something and it is not broken.

**Comment by mircokroon** [comment]
Great, thanks! I think the blocks disappearing may be due to them being placed after the chunks were loaded? It doesn't actually update existing chunks with newly placed blocks currently (wouldn't be too hard to do but it seems relatively low priority). If you leave the area and come back it should show them. 

I didn't add them to the minimap yet though, I'll do that before merging this.

**Pull request merged**
